Oluwasetemi/altschool-opensource-names

- names.txt
> Joshua added his name

- names.txt
Contributed to the Github workflow Live Class. An awesome job being done by @Oluwasetemi. Please review and merge
> Added my name, Emmanuel Oloke

- names.txt
Kindly review and add my name to the altschool-opensource-names
> Abdulbasit Yusuf added his name

- names.txt
> Name Addition

- names.txt
> Added Omafovbe

- names.txt
> Add name to list

- names.txt
> Contribution

- names.txt
This is my last try. I hope it works this time.
> Updated the names.txt file

- names.txt
added my name Oladeji Adeshina to the list
> added my name to the list

- names.txt
Kindly merge my pull request to the base repository
> Added my name to names.txt file

- names.txt
> ch: add my name as requested

- names.txt
> Added Adetunji Igbatayo to list

- names.txt
> adding clinton mekwunye

- names.txt
> add my name to list

- names.txt
> I just added my name

- names.txt
I added my name. I hope the merge request works because I'm having a bit of an issue.
> Added Teniola Olowookere

- names.txt
> add Ayodeji

- names.txt
I added my name to the names.txt file
> Added my Name

- names.txt
####Changes to Names.txt file
Added name: Marrilyn Olungweonwi to line 84
> added name:Marrilyn Olungweonwi

- names.txt
Added my name to Altschool Opensource contribution.
> Fix: Added my name to Altschool Opensource contribution.

- names.txt
> ft--kingsleyumujeyan name added

- README.md
With the updated README.md, we can point contributors to a guide as we close older pull requests
> Update readme.md with descriptive photos

- names.txt
I noticed that someone duplicated my name on the list, so I proceeded to remove it. Please review and merge.
And do let me know if made any mistakes along the way. Thanks.
> removed duplicate name

- names.txt
added Nnah Ifeoma Goodness to names.txt
> I made my first commit

- names.txt
Add "Micheal Adeniran" to names.txt
> Add "Micheal Adeniran" to names.txt

- names.txt
got your mail and corrected my pr. thank you!
> Add Peace to the list of names

- names.txt
add "marliyya ubam" to names.txt
> Adding new name

- names.txt
I added my name to the text file
> name added

- names.txt
Hi Setemi kindly merge my pull request, thank you love your work.
> Added my name Matthew Mosimabale Tarfa

- README.md
- names.txt
I added four pretty good looking opensource icons to the Readme file, you may like them. Please add my pR if you do.
I added my name to the list in the name text file also. Cheers
> Add opensource icons to Readme and Add Raji Risikat Yewande to name list pls

- names.txt
This PR is to add my name to the list of contributors.
> Add Eseosa to the list of names

- names.txt
i got your mail; made corrections
> Adding osayuki

- names.txt
I added my name to the names.txt file
> Added Ayomide Joshua Fabiyi to the list of names

- names.txt
Adding Theresa Ottah to names.txt
> Adding Theresa Ottah to names.txt 

- names.txt
Made some modification base on the Email I got, Updated my name due to the README.md
> Adding my name

- names.txt
This PR is to add my name to the open source project by Altschool
> Add Olumese Steve-John to the list of names

- names.txt
> Add David Ottache to the list of names

- names.txt
I added my name to the name.txt file
> Add <Abdulkareem-Babatunde> to the list of names

- names.txt
Added Anietie Akpanumoh to the list of names
> Added Anietie Akpanumoh to the list of names

- names.txt
Added Esther Ibom to the List of names.
> Adding name

- names.txt
Kindly add my name. Thanks Setemi, the screen shots were very useful.
> Add <Sulaiman Yahaya Adamu> to the list of names

- names.txt
This PR add my name to the list of AltSchool Contributors.
> Add my name

- names.txt
I updated my name to the names.txt file
> I updated my branch

- names.txt
Hello Setemi,
I have added my name to the list .Please approve.
> Add Fatimah Badmus to the list of names

- names.txt
I have added my name to names.txt.
Kindly merge my  PR.
> I addede my name to names.txt

- names.txt
I have added my name to the list.
> Added name to the list

- .gitignore
- names.txt
I was able to add my name: **POPOOLA EMMANUEL** to the middle of the names
> Added Popoola Emmanuel to the list of names

- names.txt
> Included my name

- names.txt
Added `Maxwell Ahmadu` to the list
> added my name Maxwell Ahmadu

- names.txt
I updated the names.txt by including my name
> In the names.txt, I added my name

- names.txt
This PR adds my name to the list of AltSchool-opensource-names
> added my name to the names list

- names.txt
- Included my name to the names.txt file
> added my name to names.txt

- names.txt
Had to close the former pull request and undergo the processes all over again.
> Contributed to the list of names

- names.txt
> Add Akikoromo-Emmanuel-Ebifagha to the list of names

- names.txt
> Add <ola-kazeem> to list of names

- names.txt
> i added my name again

- names.txt
> Sanusi Waris

- names.txt
please add my name to the list
> Added my name  to the list of names

- names.txt
Please add Olutayo Babem to the list of names
> Add Olutayo Babem to the list of names

- names.txt
> Add George Owoh to the list of names

- names.txt
I added my name adeyanju fawaz to the list
> i added my name ADEYANJU FAWAZ

- names.txt
hoping to get my name added. Thanks
> Add Olagunju Oluwkolade to the list of names. Thanks

- names.txt
I added my name to the list of names. Thank you!
> Add Blessing Nfeh to the list of names

- names.txt
> Added my name Frank Joseph to the list of names

- names.txt
I added Tobiloba Ibraheem to list of names. Please Approve!!!
> I added Tobiloba Ibraheem to list of names

- README.md
- names.txt
I just added my name to the list of contributors. I encountered some hitches which led me to also updating the **README** file. Thank you for the experience, knowledge, help and push.
> Add Adaobi to the list of names and README update

- names.txt
Please add my name to the list. Thank you.
> Add Sarah Daniel to the list of names

- names.txt
Added "Samuel Oso" to the names.txt file.
> Added Samuel Oso to the list of names

- names.txt
Looking forward to adding more functionalities to the repo for future altschoolers but for now, just my name ☺️
> simply added my name to the list

- names.txt
I just updated the names.txt file with my name "Oyeka nonso christopher". Pls help accept my pull request
> added Oyeka nonso christopher to names.txt

- names.txt
This PR adds my name to the altschool devs list you created...you are the Boss
> add: i added my name to the list

- names.txt
> kperusi added his name .

- names.txt
> Add Momoh Ridwan Ohiani to the list of names

- names.txt
I'm adding my name again, because the previous one wasn't merge, please help merge this time around
> i added my name

- names.txt
> Add <Michael Chijioke Nweke> to the list of names

- names.txt
I added my name to the list of names.
> Add Hafiz Adeyinka Junaid to the list of names

- names.txt
> add Egu Chinedu to the list of names

- names.txt
Practicing open source contributions by adding my name
> Add Olumide Gbadegesin to the list of names

- names.txt
I added my name to the list of Altschool Opensource names.
> Added my name, Owhologbo

- names.txt
> Add Adeagbo Toheeb to the list of names

- names.txt
I just added my name to names.txt
> I added Olubunmi Oluwatobi James to the list of names

- names.txt
> adding-new-name

- names.txt
Hi administrators, kindly add my name to the list of names. Thank you!!!!!
> Add Linda Akorfa Abotsigah to the list of names

- testDuplicate.js
Resolve issue https://github.com/Oluwasetemi/altschool-opensource-names/issues/738.
> FIX: Duplicate check case-sensitivity

- names.txt
Successfully changed the branch. Kindly merge.
> Added "Eugene Ozuem" to the names.

- names.txt
Hello, Kindly review and review merge accordingly.
> Added Muhammad Ibrahim

- names.txt
Please merge my pull request. Thanks
> added my name to name.txt

- names.txt
> Add Aghwotu Onoriode Akpobo to the list of names

- names.txt
My first open source contribution
> I added my name to the list of names

- names.txt
Added "Alonge Wonuola" to names.txt
> Updates names.txt

- names.txt
> Add: Elizabeth Agwa to the list of names

- names.txt
Hello Admin,
Please add my name to the list.
Thank you.
> Add Durojaye Sekinat Abisola to the list of names

- names.txt
> Created a new branch "name-to-list"
> Added my name Adebanjo Abolanle Mary in the names.txt file
> Added Adebanjo Abolanle Mary to the list of names

- names.txt
I added my name to the names.txt file.
> Adding Munir Adavize Abdullahi to names.txt

- names.txt
Kindly Add my name `Onosemuode Ikuesiri Kola`
>  Added my name: Onosemuode Ikuesiri Kola

- names.txt
This PR seeks to add the name ```Favour Oluchi Boi``` to the list of names in the ```names.txt``` file
> Add Favour Oluchi Boi to the list of names

- names.txt
> I have added my name on a separate branch

- names.txt
> Add Emmanuel Odedele to the list of names

- names.txt
> second commit

- names.txt
I added my name to the list of names.
> Added 'Gregory Ogbemudia' to the list of names

- names.txt
Hi Setemi.
Thank you for always coming through.
Please merge my PR.
> Tech Girl added her name

- names.txt
> Please Add Mediat Yusuff to the list of names

- names.txt
Added name of new AltSchool student to the names.txt file
> added new user name

- names.txt
> Second version

- names.txt
> new commit

- names.txt
> Added <Obioma Obijiaku> to the list of names

- names.txt
> Add Idowu-Olakunle to the list

- names.txt
This is my fourth shot at this. Pls add. Cheers.
> Add Olabode Adetula to names.txt

- names.txt
this is my third attempt at adding my name, i missed it all along but i just got a hang of it... practice, they say, makes perfect.
> i added my name to the list

- names.txt
Added "Isaac Imonivwerha" to names.txt
> Added a name to names.txt

- names.txt
I added my name "Osita Amaechi" to altschool names file.
> Add altchool opensource names

- names.txt
> add Chigozie Oziri to the list of names

- index.html
- resources/main.css
- resources/script.js
I added the theme toggle functionality by editing the index.html, main.css and script.js files
> Adding the toggle theme functionality

- searchContributors.mjs
> Wrote search contributors functionality

- names.txt
> Add <Anyi Joy Oluomachukwu> to the list of names

- names.txt
> Ojo Stephen

- names.txt
> added name to names.txt

- names.txt
Finally able to grasp this. Thank you Setemi.
> I added Elijah Ishaku
